# Site settings
title: ericzheng's blog
email: iericzheng@foxmail.com
description: 前端开发工程师 技术宅 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eric_Cheng_js
github_username:  zhengjunwei

# Build settings
markdown: kramdown
